site_name: Convention
site_author: Tuan Le
copyright: 'Tuan Le - 2019'

nav:
- Home: 'index.md'
- RFC 2119: 'rfc_2119.md'
- PHP:
  - 'PSR-1 Basic Coding Standard': 'php/01_PSR_1_basic_coding_standard.md'
  - 'PSR-2 Coding Style Guide': 'php/02_PSR_2_coding_style_guide.md'
  - 'PSR-4 Autoloader': 'php/04_PSR_4_autoloader.md'
- Laravel:
  - 'Folder Structure': 'laravel/index.md'

theme:
  name: null
  custom_dir: material/
  language: vi
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

markdown_extensions:
  - toc:
      permalink: '#'
  - attr_list
  - admonition
  - tables
  - codehilite

extra_css:
  - css/extra.css

plugins:
  - search